name: Limit Duplications

on: [push, pull_request]

jobs:
  limit-duplications:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: No Duplication beyond 4 lines and 55 tokens
      run: jscpd ./ --min-lines 4 --min-tokens 55 --threshold 0 --mode strict
      
